r"""Builds src/data/ForceCleanupFlags.inc: for each 1491.50 singleplayer
script, the force-cleanup flags it checks, from the literal arguments of
HAS_FORCE_CLEANUP_OCCURRED in its decompiled source:

    python tools/extract_cleanup_flags.py src\data [..\Scripts\1491.50\script_rel]

A script runs its cleanup when FORCE_CLEANUP / FORCE_CLEANUP_FOR_THREAD_WITH_THIS_ID
is called with a flag it checks, so the Script Monitor defaults to these.
(Rampage always passes 0x800, which only 9 of these scripts check.)
Each row is { "<script>", 0x<mask> }; scripts that check none are left out.
"""
import glob, os, re, sys

def main(dst, src=os.path.join("..", "Scripts", "1491.50", "script_rel")):
    rows = []
    for path in sorted(glob.glob(os.path.join(src, "*.ysc.c"))):
        with open(path, encoding="utf-8", errors="replace") as f:
            masks = [int(m) for m in re.findall(r"HAS_FORCE_CLEANUP_OCCURRED\((\d+)\)", f.read())]
        mask = 0
        for m in masks:
            mask |= m
        if mask:
            rows.append((os.path.basename(path)[:-len(".ysc.c")], mask))
    lines = ["// Generated by tools/extract_cleanup_flags.py from the decompiled 1491.50",
             "// scripts; don't edit by hand."]
    lines += ['{ "%s", 0x%X },' % row for row in rows]
    with open(os.path.join(dst, "ForceCleanupFlags.inc"), "w", encoding="utf-8", newline="\r\n") as f:
        f.write("\n".join(lines) + "\n")
    print("ForceCleanupFlags.inc", len(rows))

if __name__ == "__main__":
    main(*sys.argv[1:3])
