r"""Builds src/data/Emotes.inc from alloc8or's eEmote enum (the doc that
alloc8or's TASK_PLAY_EMOTE_WITH_HASH comment links):

    python tools/extract_emotes.py src\data [eEmote.txt]

Without a local file it downloads https://alloc8or.re/rdr3/doc/enums/eEmote.txt.
Each row is { "NAME", type }, the type being eEmoteType (from the same
native's comment), picked by the name's prefix. Animal emotes (BOAR_EMOTE,
...) are left out. Nothing here comes from Rampage.
"""
import os, re, sys, urllib.request

URL = "https://alloc8or.re/rdr3/doc/enums/eEmote.txt"

# eEmoteType: REACT 0, ACTION 1, TAUNT 2, GREET 3, TWIRL_GUN 4, DANCE_FLOOR 5.
TYPES = [("KIT_EMOTE_REACTION_", 0), ("KIT_EMOTE_ACTION_", 1), ("KIT_EMOTE_TAUNT_", 2),
         ("KIT_EMOTE_GREET_", 3), ("KIT_EMOTE_TWIRL_", 4), ("KIT_EMOTE_DANCE_", 5)]

def main(dst, src=None):
    if src:
        with open(src, encoding="utf-8") as f:
            text = f.read()
    else:
        request = urllib.request.Request(URL, headers={"User-Agent": "curl/8"})  # the default agent gets a 403
        text = urllib.request.urlopen(request).read().decode("utf-8")
    rows = []
    for name in re.findall(r"^\s*([A-Z0-9_]+)\s*=", text, re.M):
        for prefix, kind in TYPES:
            if name.startswith(prefix):
                rows.append((kind, name))
    lines = ["// Generated by tools/extract_emotes.py from alloc8or's eEmote enum;",
             "// don't edit by hand."]
    lines += ['{ "%s", %d },' % (name, kind) for kind, name in sorted(rows)]
    with open(os.path.join(dst, "Emotes.inc"), "w", encoding="utf-8", newline="\r\n") as f:
        f.write("\n".join(lines) + "\n")
    print("Emotes.inc", len(rows))

if __name__ == "__main__":
    main(*sys.argv[1:3])
