r"""Builds the Miscellaneous menu's lists from the game's own decompiled
scripts:

    python tools/extract_misc.py ..\Scripts\1491.50 src\data

- MusicEvents.inc: every literal passed to TRIGGER_MUSIC_EVENT or
  PREPARE_MUSIC_EVENT.
- Cutscenes.inc: mission cutscene names (<mission>_mcsN, _int, _ext,
  _rscN, _ptl), from literals with or without the "cutscene@" prefix the
  scripts add before _CREATE_ANIM_SCENE. The menu prefixes them again.
- GuardZones.inc: guard zone names, from literal arguments to the
  *_GUARD_ZONE natives plus the string a script assigns to a local it then
  passes to them.
- RelGroups.inc: relationship group names, from joaat("REL_...") literals.

Singleplayer scripts only (script_rel). Nothing here comes from Rampage.
"""
import os, re, sys

MUSIC = re.compile(r'(?:TRIGGER|PREPARE)_MUSIC_EVENT\("([^"]+)"\)')
CUTSCENE = re.compile(r'"(?:cutscene@)?([a-z]{2,8}[0-9]*_(?:mcs[0-9]+[a-z]?|int|ext|rsc[0-9]+[a-z]?|ptl))"', re.I)
ZONE_LITERAL = re.compile(r'GUARD_ZONE\w*\("([^"]+)"')
ZONE_LOCAL = re.compile(r'GUARD_ZONE\w*\((sLocal_\d+)')
REL = re.compile(r'joaat\("(REL_\w+)"\)', re.I)

def main(script_dir, out_dir):
    music, cutscenes, zones, rels = set(), set(), set(), set()
    folder = os.path.join(script_dir, "script_rel")
    for fn in os.listdir(folder):
        with open(os.path.join(folder, fn), encoding="utf-8", errors="replace") as f:
            text = f.read()
        music.update(MUSIC.findall(text))
        cutscenes.update(c.lower() for c in CUTSCENE.findall(text))
        zones.update(ZONE_LITERAL.findall(text))
        rels.update(r.upper() for r in REL.findall(text))
        for local in set(ZONE_LOCAL.findall(text)):
            zones.update(re.findall(r'\b%s = "([^"]+)"' % local, text))
    header = "// Generated by tools/extract_misc.py from the 1491.50 decompiled\n// scripts; don't edit by hand.\n"
    def write(name, items):
        with open(os.path.join(out_dir, name), "w", encoding="utf-8", newline="\r\n") as f:
            f.write(header + "".join('"%s",\n' % i for i in sorted(items)))
    write("MusicEvents.inc", music)
    write("Cutscenes.inc", cutscenes)
    write("GuardZones.inc", zones)
    write("RelGroups.inc", rels)
    print(len(music), "music events,", len(cutscenes), "cutscenes,", len(zones), "guard zones,", len(rels), "relationship groups")

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
