"""Generate src/data/Descriptions.inc: the text Rampage shows under the
selected row, keyed by (menu title, row label).

    python tools/extract_rampage_descriptions.py <inventory.json> [out.inc]

<inventory.json> is rampage_inventory_ida.py's output (see CLAUDE.md,
"Feature inventory"). Each Rampage menu API call takes a vector of
description lines (rampage_inventory.row_description reads them from the
pseudocode); the menu title is the builder's title call. Lines are joined
with "\\n" and the game's ~n~ becomes "\\n" too, since the menu wraps the
text itself. Rampage-specific wording (its folder names, its own name) is
rewritten for Rampagio by REWRITES.

Descriptions are carried over like the other names Rampage keeps in its
binary (user, 2026-10-08). Rows that are ours, or that work differently
from Rampage's, get their text from kOurs in src/Descriptions.cpp, which
wins over this table. Regenerate rather than edit.
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rampage_inventory import row_label, row_description  # noqa: E402

# (pattern, replacement) applied to every description line, in order.
REWRITES = [
    (r"Folder: RampageFiles\\*Saved (Teleports|Outfits|Horses)\.?", r"File: Rampagio_\1.json"),
    (r"Files get saved in the RampageFiles folder\.", "Files are saved next to Rampagio.json."),
    (r"RampageFiles\\\\?Lists\\\\?", ""),
    (r"RampageFiles\\\\?", ""),
    (r"\b[Rr]ampage\b", "Rampagio"),
]

# Menus Rampagio doesn't have: Rampage's own credits and windows, and the
# tabled areas (CLAUDE.md, Next steps); regenerate if they come back.
SKIP_MENUS = {"About Rampage", "Window Manager", "Debug", "Script Tools"}

# Rows whose label isn't fixed text (counters, formatted values).
SKIP_LABEL = re.compile(r"\{\d*\}|^\s*$")


def c_string(s):
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def clean(line):
    for pattern, repl in REWRITES:
        line = re.sub(pattern, repl, line)
    return line.replace("~n~", "\n").strip()


def main(inv_path, out_path):
    inv = json.load(open(inv_path))
    titles = {}
    for r in inv["rows"]:
        if r["api"] == "title" and r["sub"] not in titles:
            # Drop a state note some titles carry ("Time ~COLOR_RED~[Mission is active]").
            titles[r["sub"]] = re.sub(r"\s*~COLOR_\w+~\[.*\]$", "", row_label(r))
    entries = {}
    for r in inv["rows"]:
        if r["api"] == "title":
            continue
        lines = [clean(l) for l in row_description(r)]
        lines = [l for l in lines if l]
        label, title = row_label(r), titles.get(r["sub"], "")
        if not lines or not title or title in SKIP_MENUS or SKIP_LABEL.search(label):
            continue
        entries.setdefault((title, label), "\n".join(lines))
    with open(out_path, "w", encoding="utf-8", newline="\r\n") as fp:
        fp.write("// Generated by tools/extract_rampage_descriptions.py from Rampage's menu\n")
        fp.write("// builders: { menu title, row label, description }. Regenerate rather than edit.\n")
        for (title, label), text in sorted(entries.items()):
            fp.write("{ %s, %s, %s },\n" % (c_string(title), c_string(label), c_string(text)))
    print("%d descriptions -> %s" % (len(entries), out_path))


if __name__ == "__main__":
    if len(sys.argv) not in (2, 3):
        sys.exit(__doc__)
    here = os.path.dirname(os.path.abspath(__file__))
    main(sys.argv[1], sys.argv[2] if len(sys.argv) == 3 else os.path.join(here, "..", "src", "data", "Descriptions.inc"))
