r"""Builds src/data/ItemNames.inc, the Give Items list, from the game's own
decompiled scripts (every joaat("...") whose name has an item prefix).

    python tools/extract_items.py ..\Scripts\1491.50\script_rel src\data\ItemNames.inc

Each line is { "Category", "internal_name", "Label" }. The menu drops
names the item database doesn't know at runtime, so prefixes may be
generous. Items the scripts only use as raw hashes are missed.
Nothing here comes from Rampage.
"""
import os, re, sys

# Name prefix -> category, in menu order. Clothing, weapons and horse
# breeds are left to their own menus.
CATEGORIES = [
    ("consumable_", "Consumables"),
    ("provision_", "Provisions"),
    ("herb_", "Herbs"),
    ("document_", "Documents"),
    ("kit_", "Kits"),
    ("upgrade_", "Upgrades"),
    ("ammo_", "Ammo"),
    ("satchel_", "Satchels"),
    ("horse_equipment_", "Horse Equipment"),
    ("saddle_", "Saddles"),
]

def label(name, prefix):
    words = name[len(prefix):].split("_")
    return " ".join(w.capitalize() if not w.isdigit() else w for w in words if w)

def main(src, dst):
    names = set()
    rx = re.compile(r'joaat\("([A-Za-z0-9_]+)"\)')
    for fn in os.listdir(src):
        if fn.endswith(".c"):
            with open(os.path.join(src, fn), encoding="utf-8", errors="replace") as f:
                names.update(n.lower() for n in rx.findall(f.read()))
    lines = []
    counts = []
    for prefix, category in CATEGORIES:
        group = sorted(n for n in names if n.startswith(prefix))
        counts.append("%s %d" % (category, len(group)))
        lines += ['{ "%s", "%s", "%s" },' % (category, n, label(n, prefix)) for n in group]
    header = ("// Generated by tools/extract_items.py from the 1491.50 decompiled\r\n"
              "// scripts; don't edit by hand. { category, internal name, label }\r\n")
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    with open(dst, "w", encoding="utf-8", newline="") as f:
        f.write(header + "\r\n".join(lines) + "\r\n")
    print(", ".join(counts))

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
