r"""Builds src/data/RampageMapDiscoveries.inc, the map discoveries Rampage's
Recovery > Unlocks > Map Discoverables walks, from its binary.

    python tools/extract_rampage_discoveries.py <Rampage.asi> src/data/RampageMapDiscoveries.inc

Rampage keeps the names as an array of string pointers in .rdata (it
joaat()s each one at runtime). The array is found by the pointer to its
first name, then read until an entry is no longer a pointer to a MAP_
string. Needs pefile.

The names are carried over on purpose (see CLAUDE.md); nothing reads
Rampage at runtime. The menu merges this list with MapDiscoveries.inc
(the names the game scripts use). Output rows (as MapDiscoveries.inc):
    { "<name>", "<label>" },
"""
import struct
import sys

import pefile

FIRST = b"MAP_ANIMAL_FISH_BASS_LARGE_MOUTH\0"


def tidy(name, prefix="MAP_"):
    words = name[len(prefix):].split("_")
    return " ".join(w.capitalize() if not w.isdigit() else w for w in words if w)


def main(asi, out):
    pe = pefile.PE(asi, fast_load=True)
    base = pe.OPTIONAL_HEADER.ImageBase
    data = pe.__data__
    off = data.find(FIRST)
    if off < 0:
        raise SystemExit("first name not found")
    first = base + pe.get_rva_from_offset(off)
    table = data.find(struct.pack("<Q", first))
    if table < 0:
        raise SystemExit("table not found")

    def string_at(va):
        try:
            raw = pe.get_data(va - base, 128).split(b"\0")[0]
        except Exception:
            return None
        return raw.decode("ascii") if raw.startswith(b"MAP_") and raw.isascii() else None

    names = []
    while True:
        name = string_at(struct.unpack_from("<Q", data, table)[0])
        if not name:
            break
        names.append(name)
        table += 8

    with open(out, "w", newline="\r\n", encoding="utf-8") as f:
        f.write("// Generated by tools/extract_rampage_discoveries.py from Rampage's Map\n")
        f.write("// Discoverables table. Regenerate rather than edit. { name, label }\n")
        for name in names:
            f.write('{ "%s", "%s" },\n' % (name, tidy(name)))
    print("RampageMapDiscoveries.inc: %d" % len(names))


if __name__ == "__main__":
    main(*sys.argv[1:3])
