r"""Builds the Recovery > Unlocks data lists from the game's own decompiled
scripts:

    python tools/extract_unlocks.py ..\Scripts\1491.50\script_rel src\data

- MapDiscoveries.inc: every map discovery the scripts name with
  joaat("MAP_<group>_...") for the discovery groups below, plus raw hashes
  the scripts pass straight to the MAP discovery natives.
  { "internal name or 0x hash", "Label" }
- UnlockNames.inc: every unlock the scripts pass by name to UNLOCK_*
  natives. { "internal name", "Label" }
- Compendium.inc: what the Discover rows walk. { "kind", "name" }:
  Herb (herb.ysc's herb types), Animal (every at_* animal type), Horse
  (every a_c_horse* model), Fish (every a_c_fish* model) and Bait (every
  upgrade_fsh_bait_* item), plus Journal (every journal_* entry, for
  Add Entries; the menu keeps those _JOURNAL_CAN_WRITE_ENTRY allows).

Discoveries and unlocks the scripts only reach through tables of raw
hashes are missed. Nothing here comes from Rampage.
"""
import os, re, sys

MAP_GROUPS = ("HIDEOUT", "HOMESTEAD", "LANDMARK", "SETTLEMENT", "SHACK", "SPECIAL", "EVENTAREA")

def tidy(name, prefix=""):
    words = name[len(prefix):].split("_")
    return " ".join(w.capitalize() if not w.isdigit() else w for w in words if w)

def joaat(s):
    h = 0
    for c in s.lower().encode():
        h = (h + c) & 0xFFFFFFFF
        h = (h + (h << 10)) & 0xFFFFFFFF
        h ^= h >> 6
    h = (h + (h << 3)) & 0xFFFFFFFF
    h ^= h >> 11
    return (h + (h << 15)) & 0xFFFFFFFF

def read_scripts(src):
    for fn in sorted(os.listdir(src)):
        if fn.endswith(".c"):
            with open(os.path.join(src, fn), encoding="utf-8", errors="replace") as f:
                yield f.read()

def write(dst, tool_note, lines):
    header = ("// Generated by tools/extract_unlocks.py from the 1491.50 decompiled\r\n"
              "// scripts; don't edit by hand. " + tool_note + "\r\n")
    with open(dst, "w", encoding="utf-8", newline="") as f:
        f.write(header + "\r\n".join(lines) + "\r\n")

def main(src, dst_dir):
    named = set()
    raw = set()
    unlocks = set()
    rx_map = re.compile(r'joaat\("(MAP_([A-Z]+)_[A-Z0-9_]+)"\)')
    rx_raw = re.compile(r'_MAP_(?:DISCOVER_REGION|DISCOVERY_SET_ENABLED|IS_DISCOVERY_ACTIVE)\((-?\d+)\)')
    rx_unlock = re.compile(r'UNLOCK_(?:IS_UNLOCKED|SET_UNLOCKED|SET_VISIBLE|IS_VISIBLE)\(joaat\("([A-Za-z0-9_]+)"\)')
    kinds = {"Animal": set(), "Horse": set(), "Fish": set(), "Bait": set(), "Journal": set()}
    rx_kind = {
        "Animal": re.compile(r'joaat\("(at_[A-Za-z0-9_]+)"\)', re.I),
        "Horse": re.compile(r'joaat\("(a_c_horse[A-Za-z0-9_]*)"\)', re.I),
        "Fish": re.compile(r'"(a_c_fish[A-Za-z0-9_]*)"', re.I),
        "Journal": re.compile(r'joaat\("(journal_[A-Za-z0-9_]+)"\)', re.I),
        "Bait": re.compile(r'joaat\("(upgrade_fsh_bait_[A-Za-z0-9_]+)"\)', re.I),
    }
    with open(os.path.join(src, "herb.ysc.c"), encoding="utf-8", errors="replace") as f:
        herbs = {n.lower() for n in re.findall(r'joaat\("(herb_[A-Za-z0-9_]+)"\)', f.read())}
    for text in read_scripts(src):
        for kind, rx in rx_kind.items():
            kinds[kind].update(n.lower() for n in rx.findall(text))
        named.update(n for n, group in rx_map.findall(text) if group in MAP_GROUPS)
        raw.update(int(n) & 0xFFFFFFFF for n in rx_raw.findall(text))
        unlocks.update(n.upper() for n in rx_unlock.findall(text))

    raw -= {joaat(n) for n in named}
    os.makedirs(dst_dir, exist_ok=True)
    maps = ['{ "%s", "%s" },' % (n, tidy(n, "MAP_")) for n in sorted(named)]
    maps += ['{ "0x%08X", "0x%08X" },' % (h, h) for h in sorted(raw)]
    write(os.path.join(dst_dir, "MapDiscoveries.inc"), "{ name or 0x hash, label }", maps)
    unl = ['{ "%s", "%s" },' % (n, tidy(n, "SP_" if n.startswith("SP_") else "")) for n in sorted(unlocks)]
    write(os.path.join(dst_dir, "UnlockNames.inc"), "{ name, label }", unl)
    comp = ['{ "Herb", "%s" },' % n for n in sorted(herbs)]
    for kind in ("Animal", "Horse", "Fish", "Bait", "Journal"):
        comp += ['{ "%s", "%s" },' % (kind, n) for n in sorted(kinds[kind])]
    write(os.path.join(dst_dir, "Compendium.inc"), "{ kind, name }", comp)
    print("compendium: herbs %d, %s" % (len(herbs), ", ".join("%s %d" % (k, len(v)) for k, v in kinds.items())))
    print("map discoveries %d named + %d raw, unlocks %d" % (len(named), len(raw), len(unlocks)))

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
