r"""Builds src/data/ScriptNames.inc, the Script Monitor's name table, from the
file names of the decompiled 1491.50 singleplayer scripts:

    python tools/extract_script_names.py src\data [..\Scripts\1491.50\script_rel]

Each row is { joaat(name), "name" }. The game keeps only a script's name
hash (scrThreadContext::m_ScriptHash, scrProgram::m_NameHash), so this is
how the monitor shows names; src/debug/ScriptNames.cpp loads it into a
hash map. Online scripts (script_mp_rel) are left out.
"""
import os, sys

def joaat(text):
    h = 0
    for c in text.lower().encode():
        h = (h + c) & 0xFFFFFFFF
        h = (h + (h << 10)) & 0xFFFFFFFF
        h ^= h >> 6
    h = (h + (h << 3)) & 0xFFFFFFFF
    h ^= h >> 11
    return (h + (h << 15)) & 0xFFFFFFFF

def main(dst, src=os.path.join("..", "Scripts", "1491.50", "script_rel")):
    names = sorted({f[:-len(".ysc.c")] for f in os.listdir(src) if f.endswith(".ysc.c")})
    rows = sorted((joaat(n), n) for n in names)
    hashes = [h for h, _ in rows]
    if len(set(hashes)) != len(hashes):
        sys.exit("hash collision in script names")
    lines = ["// Generated by tools/extract_script_names.py from the 1491.50",
             "// singleplayer script file names; don't edit by hand."]
    lines += ['{ 0x%08X, "%s" },' % row for row in rows]
    with open(os.path.join(dst, "ScriptNames.inc"), "w", encoding="utf-8", newline="\r\n") as f:
        f.write("\n".join(lines) + "\n")
    print("ScriptNames.inc", len(rows))

if __name__ == "__main__":
    main(*sys.argv[1:3])
