r"""Builds the Player submenus' name lists from the game's own decompiled
scripts:

    python tools/extract_player_lists.py ..\Scripts\1491.50\script_rel src\data

Each output is a sorted list of "name", lines:

- WalkStyles.inc: literal names passed to _SET_PED_DESIRED_LOCO_MOTION_TYPE.
- Scenarios.inc: joaat("...") names of ped scenarios (WORLD_HUMAN_,
  PROP_HUMAN_, ...). Ransack, shop, vehicle and animal scenarios are left
  out because the player ped can't use them.
- Moods.inc: facial idle anim names starting with "mood_" (not the
  joaat("MOOD_<character>") hashes, which are something else).
- PostFx.inc: literal names passed to the ANIMPOSTFX_ natives.
- Timecycles.inc: literal names passed to the *TIMECYCLE_MODIFIER* natives.
- DamagePacks.inc: literal names passed to APPLY_PED_DAMAGE_PACK.

Names only reached through script data (struct fields, arrays) are
missed. Nothing here comes from Rampage.
"""
import os, re, sys

SCENARIO_PREFIXES = ("WORLD_HUMAN_", "WORLD_PLAYER_", "WORLD_CAMP_", "PROP_HUMAN_",
                     "PROP_PLAYER_", "PROP_CAMP_", "GENERIC_", "MP_LOBBY_")

LISTS = {
    "WalkStyles.inc": [re.compile(r'_SET_PED_DESIRED_LOCO_MOTION_TYPE\([^;"]*?, "([^"]+)"\)')],
    "Scenarios.inc": [re.compile(r'joaat\("((?:%s)[A-Za-z0-9_]+)"\)' % "|".join(SCENARIO_PREFIXES), re.I)],
    "Moods.inc": [re.compile(r'(?<!joaat\()"(mood_[A-Za-z0-9_]+)"', re.I)],
    "PostFx.inc": [re.compile(r'ANIMPOSTFX_\w*\("([^"]+)"')],
    "Timecycles.inc": [re.compile(r'TIMECYCLE_MODIFIER\w*\("([^"]+)"')],
    "DamagePacks.inc": [re.compile(r'APPLY_PED_DAMAGE_PACK\([^;"]*?, "([^"]+)"')],
}

# Names that differ only in case are one name to the game; keep one spelling.
UPPER = {"Scenarios.inc"}

def main(src, dst):
    found = {name: {} for name in LISTS}
    for fn in sorted(os.listdir(src)):
        if not fn.endswith(".c"):
            continue
        with open(os.path.join(src, fn), encoding="utf-8", errors="replace") as f:
            text = f.read()
        for name, patterns in LISTS.items():
            for rx in patterns:
                for m in rx.findall(text):
                    v = m.upper() if name in UPPER else m
                    found[name].setdefault(v.lower(), v)
    for name, values in found.items():
        lines = ["// Generated by tools/extract_player_lists.py from the 1491.50 decompiled",
                 "// scripts; don't edit by hand."]
        lines += ['"%s",' % v for _, v in sorted(values.items())]
        with open(os.path.join(dst, name), "w", encoding="utf-8", newline="\r\n") as f:
            f.write("\n".join(lines) + "\n")
        print(name, len(values))

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
