r"""Builds src/data/NativeList.inc, the Script Monitor's native picker, from
alloc8or's native header (external/ScriptHookSDK/inc/natives.h):

    python tools/extract_native_list.py src\data

Each row is { "NAMESPACE", "NAME", hash, kind, "return type", "parameters",
parameter count }. kind is the NativeReturn the hook UI offers for the
return type: 0 void, 1 int-like (BOOL, int, Hash and the handle types),
2 float, 3 Vector3, 4 string, 5 pointer. Regenerate after bumping the
ScriptHookSDK submodule.
"""
import os, re, sys

HEADER = os.path.join("external", "ScriptHookSDK", "inc", "natives.h")
DECL = re.compile(r"NATIVE_DECL (.+?) ([A-Za-z_0-9]+)\((.*?)\) \{.*?invoke<.*?>\((0x[0-9A-Fa-f]+)")

def kind(ret):
    if ret == "void": return 0
    if ret == "float": return 2
    if ret == "Vector3": return 3
    if ret in ("const char*", "char*"): return 4
    if ret.endswith("*"): return 5
    return 1

def main(dst):
    rows, namespace = [], None
    with open(HEADER, encoding="utf-8") as f:
        for line in f:
            m = re.match(r"namespace ([A-Z_0-9]+)", line)
            if m:
                namespace = m.group(1)
                continue
            m = DECL.search(line)
            if not m:
                continue
            ret, name, params, hash_ = m.groups()
            count = 0 if not params.strip() else params.count(",") + 1
            rows.append('{ "%s", "%s", %sull, %d, "%s", "%s", %d },' % (
                namespace, name, hash_.upper().replace("0X", "0x"), kind(ret), ret, params, count))
    lines = ["// Generated by tools/extract_native_list.py from alloc8or's natives.h;",
             "// don't edit by hand."] + rows
    with open(os.path.join(dst, "NativeList.inc"), "w", encoding="utf-8", newline="\r\n") as f:
        f.write("\n".join(lines) + "\n")
    print("NativeList.inc", len(rows))

if __name__ == "__main__":
    main(*sys.argv[1:2])
