r"""Generates src/data/LegendaryZones.inc: where each story legendary animal's
hunting zone is, in Legendaries.h's zone order.

    python tools/extract_legendary_zones.py <ymt dir> <script_rel dir> src/data/LegendaryZones.inc

The zones aren't in the scripts: each hunting_zone_<animal>.ysc is a world
scenario point script started from a point in the hunting_<region>.ymt
scenario files (x64/levels/rdr3/scenario/ in update_4.rpf). Extract them
with the RDR2 RPF Tool's headless mode, one per region:

    "RDR2 RPF Tool.exe" --extract <game>/update_4.rpf x64/levels/rdr3/scenario/hunting_bay.ymt <ymt dir>/hunting_bay.ymt

(regions: bay bgv blu cml gap grz gzw hen rio roa scm). The .ymt files are
RSC8 resources; this reads the points as the 16-byte aligned float vectors
with map coordinates in the data section (offset >= 0x900, after the
region's bounding box), which holds 16 points over the 11 files.

Each point is matched to a script by the coordinates the script itself
uses near its zone (clue spots, volumes): coordinates shared by more than
two hunting_zone scripts (shops, camps) are ignored, then each script must
have exactly one point within 400 m of its own coordinates, and no point
may be claimed twice. The zone index is the script's own (the
"*uParam0 = N;" that opens its zone settings), which is
the Global_40.f_9319 index.
"""
import collections
import glob
import os
import re
import struct
import sys


def read_points(ymt_dir):
    points = []
    for path in sorted(glob.glob(os.path.join(ymt_dir, "hunting_*.ymt"))):
        data = open(path, "rb").read()
        for o in range(0x900, len(data) - 12, 16):
            x, y, z = struct.unpack_from("<fff", data, o)
            if all(v == v for v in (x, y, z)) and -7500 < x < 4000 and -6000 < y < 2500 \
                    and -100 < z < 1200 and abs(x) + abs(y) > 100 and abs(z) > 1:
                points.append((os.path.basename(path), x, y, z))
    return points


def zone_index(text):
    # The zone settings function: "*uParam0 = <zone>;" followed by its
    # other fields (uParam0->f_N = ...). Must be the only such value.
    found = {int(n) for n in re.findall(r"\n\t\*uParam0 = (\d+);\n\tuParam0->f_", text)}
    return found.pop() if len(found) == 1 else None


def main(ymt_dir, script_dir, out_path):
    points = read_points(ymt_dir)
    num = r"(-?\d+\.\d+)f"
    vec = re.compile(num + ", " + num + ", " + num)
    scripts = {}
    seen = collections.Counter()
    for path in sorted(glob.glob(os.path.join(script_dir, "hunting_zone_*.ysc.c"))):
        text = open(path, encoding="utf-8", errors="ignore").read()
        name = os.path.basename(path)[:-len(".ysc.c")]
        coords = {(round(float(m.group(1)), 1), round(float(m.group(2)), 1)) for m in vec.finditer(text)}
        scripts[name] = (zone_index(text), coords)
        seen.update(coords)

    zones = {}
    claimed = {}
    for name, (index, coords) in scripts.items():
        near = collections.Counter()
        for x, y in coords:
            if seen[(x, y)] > 2:
                continue
            for i, (_, px, py, _) in enumerate(points):
                if (px - x) ** 2 + (py - y) ** 2 < 400 ** 2:
                    near[i] += 1
        if index is None or len(near) != 1:
            sys.exit(f"{name}: zone index {index}, candidate points {dict(near)}")
        point = next(iter(near))
        if point in claimed:
            sys.exit(f"{name}: point {points[point]} already claimed by {claimed[point]}")
        claimed[point] = name
        zones[index] = (name, points[point])

    if sorted(zones) != list(range(16)):
        sys.exit(f"expected zones 0..15, got {sorted(zones)}")

    with open(out_path, "w", encoding="utf-8", newline="\r\n") as out:
        out.write("// Generated by tools/extract_legendary_zones.py from the hunting_*.ymt\n")
        out.write("// scenario points and the hunting_zone_* scripts. { x, y, z }, by zone index\n")
        out.write("// (Global_40.f_9319). Regenerate rather than edit.\n")
        for index in range(16):
            name, (ymt, x, y, z) = zones[index]
            out.write(f"{{ {x:.2f}f, {y:.2f}f, {z:.2f}f }}, // {index:2} {name} ({ymt})\n")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    main(*sys.argv[1:])
