r"""Builds the vehicle lists from the game's own decompiled scripts:

    python tools/extract_vehicles.py ..\Scripts\1491.50 src\data

- VehicleModels.inc: every short joaat("...") name (at most one
  underscore) in script_rel and script_mp_rel that looks like a vehicle
  (wagon, coach, cart, boat, ...).
  Some aren't vehicle models; the menus drop those at runtime with
  IS_MODEL_A_VEHICLE.
- VehiclePropsets.inc: { "name", light } for joaat("pg_...") propset
  names that belong to vehicles (teamster upgrades, pg_veh_..., ...);
  light is true for the light/lantern sets, which go through
  _ADD_LIGHT_PROP_SET_TO_VEHICLE.
- TrainConfigs.inc: integer train config hashes passed to
  _CREATE_MISSION_TRAIN and the train config natives, with the joaat name
  when some string literal in the scripts hashes to it.

Nothing here comes from Rampage.
"""
import os, re, sys

JOAAT = re.compile(r'joaat\("([A-Za-z0-9_]+)"\)')
LITERAL = re.compile(r'"([A-Za-z0-9_]{3,60})"')
TRAIN_CALL = re.compile(r'(?:_CREATE_MISSION_TRAIN|_TRAIN_CONFIG\w*)\((-?\d+)')

VEHICLE_WORDS = ("wagon", "coach", "cart", "buggy", "boat", "canoe", "ship", "gatling", "cannon",
                 "balloon", "kayak", "raft", "caboose", "flatcar", "boxcar", "trolley", "skiff",
                 "pirogue", "hearse", "privatecar", "steamer", "keelboat", "handcar", "utilliwag",
                 "bountywagon", "warwagon", "stagecoach", "chuckwagon", "breach_cannon")
NOT_VEHICLE_PREFIXES = ("pg_", "p_", "s_", "mp_", "a_", "cs_", "re_", "u_", "g_", "script", "world_",
                        "prop_", "mission", "kit_", "provision_", "consumable_", "document_",
                        "upgrade_", "clothing_", "weapon_", "ammo_", "player_", "loc_")
PROPSET_WORDS = ("veh", "wagon", "coach", "cart", "teamster", "buggy", "boat")

def joaat(s):
    h = 0
    for c in s.lower().encode():
        h = (h + c) & 0xFFFFFFFF
        h = (h + (h << 10)) & 0xFFFFFFFF
        h ^= h >> 6
    h = (h + (h << 3)) & 0xFFFFFFFF
    h ^= h >> 11
    return (h + (h << 15)) & 0xFFFFFFFF

def main(script_dir, out_dir):
    names, literals, trains = set(), set(), set()
    for sub in ("script_rel", "script_mp_rel"):
        folder = os.path.join(script_dir, sub)
        for fn in os.listdir(folder):
            with open(os.path.join(folder, fn), encoding="utf-8", errors="replace") as f:
                text = f.read()
            names.update(n.lower() for n in JOAAT.findall(text))
            literals.update(LITERAL.findall(text))
            trains.update(int(v) & 0xFFFFFFFF for v in TRAIN_CALL.findall(text))
    vehicles = sorted(n for n in names
                      if any(w in n for w in VEHICLE_WORDS) and not n.startswith(NOT_VEHICLE_PREFIXES)
                      and n.count("_") <= 1 and len(n) <= 24)
    propsets = sorted(n for n in names if n.startswith("pg_") and any(w in n for w in PROPSET_WORDS))
    by_hash = {}
    for s in literals | names:
        by_hash.setdefault(joaat(s), s.lower())
    header = "// Generated by tools/extract_vehicles.py from the 1491.50 decompiled\n// scripts; don't edit by hand.\n"
    def write(name, lines):
        with open(os.path.join(out_dir, name), "w", encoding="utf-8", newline="\r\n") as f:
            f.write(header + "".join(l + "\n" for l in lines))
    write("VehicleModels.inc", ['"%s",' % n for n in vehicles])
    write("VehiclePropsets.inc", ['{ "%s", %s },' % (n, "true" if ("light" in n or "lantern" in n) else "false")
                                  for n in propsets])
    write("TrainConfigs.inc", ['{ 0x%08X, "%s" },' % (h, by_hash.get(h, "")) for h in sorted(trains)])
    print(len(vehicles), "vehicles,", len(propsets), "propsets,", len(trains), "train configs,",
          sum(1 for h in trains if h in by_hash), "named")

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
