r"""Builds the weapon component list from the game's own decompiled scripts:

    python tools/extract_weapons.py ..\Scripts\1491.50 src\data

- WeaponComponents.inc: every "COMPONENT_..." literal in the singleplayer
  scripts. Weapon > Manage Weapons > Upgrade Weapon tries each on the
  current weapon; the game ignores the ones that don't fit it.

Nothing here comes from Rampage.
"""
import os, re, sys

COMPONENT = re.compile(r'"(COMPONENT_[A-Z0-9_]+)"', re.I)

def main(script_dir, out_dir):
    names = set()
    folder = os.path.join(script_dir, "script_rel")
    for fn in os.listdir(folder):
        with open(os.path.join(folder, fn), encoding="utf-8", errors="replace") as f:
            names.update(n.upper() for n in COMPONENT.findall(f.read()))
    with open(os.path.join(out_dir, "WeaponComponents.inc"), "w", encoding="utf-8", newline="\r\n") as f:
        f.write("// Generated by tools/extract_weapons.py from the 1491.50 decompiled\n// scripts; don't edit by hand.\n")
        f.write("".join('"%s",\n' % n for n in sorted(names)))
    print(len(names), "weapon components")

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
