r"""Builds src/data/ files from tables Rampage keeps in its .rdata.

    python tools/extract_rampage_tables.py <Rampage.asi> src/data

Each table is found by the pointer to a known first name, then read
until an entry no longer points at a string with the table's prefix.
Needs pefile.

- RampageMapDiscoveries.inc: Recovery > Unlocks > Map Discoverables, an
  array of name pointers (Rampage joaat()s each at runtime).
  { "<name>", "<label>" }, the same rows as MapDiscoveries.inc.
- LawDispatchRegions.inc: Spawner > Law Dispatch Spawner, entries of
  { name pointer, law region hash, state hash } (the two hashes go to
  _SET_LAW_REGION before the response is dispatched; 0 means none).
  { "<name>", 0x<region>, 0x<state> }

The names and hashes are carried over on purpose (see CLAUDE.md);
nothing reads Rampage at runtime.
"""
import os
import struct
import sys

import pefile


def tidy(name, prefix):
    words = name[len(prefix):].split("_")
    return " ".join(w.capitalize() if not w.isdigit() else w for w in words if w)


class Image:
    def __init__(self, path):
        self.pe = pefile.PE(path, fast_load=True)
        self.base = self.pe.OPTIONAL_HEADER.ImageBase
        self.data = self.pe.__data__

    def string(self, va, prefix):
        try:
            raw = self.pe.get_data(va - self.base, 128).split(b"\0")[0]
        except Exception:
            return None
        return raw.decode("ascii") if raw.startswith(prefix) and raw.isascii() else None

    def table(self, first, prefix, stride):
        """Offsets of the entries of the table whose first entry names `first`."""
        off = self.data.find(first + b"\0")
        while off > 0 and self.data[off - 1] != 0:
            off = self.data.find(first + b"\0", off + 1)
        if off < 0:
            raise SystemExit("%s not found" % first)
        va = self.base + self.pe.get_rva_from_offset(off)
        entry = self.data.find(struct.pack("<Q", va))
        if entry < 0:
            raise SystemExit("table of %s not found" % first)
        while self.string(struct.unpack_from("<Q", self.data, entry)[0], prefix):
            yield entry, self.string(struct.unpack_from("<Q", self.data, entry)[0], prefix)
            entry += stride


def write(path, note, lines):
    with open(path, "w", newline="\r\n", encoding="utf-8") as f:
        f.write("// Generated by tools/extract_rampage_tables.py from Rampage's\n")
        f.write("// %s. Regenerate rather than edit.\n" % note)
        f.write("".join(l + "\n" for l in lines))
    print("%s: %d" % (os.path.basename(path), len(lines)))


def main(asi, dst):
    img = Image(asi)
    write(os.path.join(dst, "RampageMapDiscoveries.inc"), "Map Discoverables table. { name, label }",
          ['{ "%s", "%s" },' % (n, tidy(n, "MAP_"))
           for _, n in img.table(b"MAP_ANIMAL_FISH_BASS_LARGE_MOUTH", b"MAP_", 8)])
    rows = []
    for off, name in img.table(b"LAW_CUSTOM_MUD3B", b"LAW_", 16):
        region, state = struct.unpack_from("<II", img.data, off + 8)
        rows.append('{ "%s", 0x%08X, 0x%08X },' % (name, region, state))
    write(os.path.join(dst, "LawDispatchRegions.inc"),
          "Law Dispatch Spawner table. { response, law region, state }", rows)


if __name__ == "__main__":
    main(*sys.argv[1:3])
