r"""Builds the Recovery > Collectibles location lists the game doesn't
expose through its collectable natives, from the decompiled scripts:

    python tools/extract_collectibles.py ..\Scripts\1491.50\script_rel src\data

- Dreamcatchers.inc: the 20 dreamcatchers' coordinates, by index.
  discoverable_generic_location maps the world brain
  WB_DISCO_DREAMCATCHERS to a discoverable id, and its coordinate
  function (Vector3 func_N(var, int)) returns each one's position under
  `case <id>:` / `case <index>:`. { x, y, z }

Dino bones and rock carvings aren't here: the menu reads those from the
game's collectable categories at runtime. Nothing here comes from Rampage.
"""
import os, re, sys

SCRIPT = "discoverable_generic_location.ysc.c"

def block_after(text, start):
    """The text of the switch block that opens at the first '{' after start."""
    i = text.index("{", start)
    depth = 0
    for j in range(i, len(text)):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
            if depth == 0:
                return text[i:j + 1]
    raise ValueError("unbalanced braces")

def main(src, dst_dir):
    with open(os.path.join(src, SCRIPT), encoding="utf-8", errors="replace") as f:
        text = f.read()
    m = re.search(r'case joaat\("WB_DISCO_DREAMCATCHERS"\):\s*return (-?\d+);', text)
    if not m:
        sys.exit("WB_DISCO_DREAMCATCHERS not found")
    disco = m.group(1)
    point = re.compile(r'case (\d+):\s*return (-?[\d.]+)f, (-?[\d.]+)f, (-?[\d.]+)f;')
    found = None
    for fm in re.finditer(r'^Vector3 func_\d+\(var uParam0, int iParam1\)', text, re.M):
        body = block_after(text, fm.end())
        cm = re.search(r'case %s:' % re.escape(disco), body)
        if not cm:
            continue
        # The case's own body runs to its `break;` (an inner switch on
        # iParam1 has no breaks, only returns).
        case_body = body[cm.end():body.index("break;", cm.end())]
        found = sorted((int(i), x, y, z) for i, x, y, z in point.findall(case_body))
        if found:
            break
    if not found or [p[0] for p in found] != list(range(len(found))):
        sys.exit("dreamcatcher coordinates not found")
    lines = ["{ %sf, %sf, %sf }," % (x, y, z) for _, x, y, z in found]
    header = ("// Generated by tools/extract_collectibles.py from the 1491.50 decompiled\r\n"
              "// scripts (%s); don't edit by hand.\r\n" % SCRIPT)
    with open(os.path.join(dst_dir, "Dreamcatchers.inc"), "w", encoding="utf-8", newline="") as f:
        f.write(header + "\r\n".join(lines) + "\r\n")
    print("Dreamcatchers.inc: %d" % len(lines))

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
