r"""Builds the Player submenus' name lists from the game's own decompiled
scripts:

    python tools/extract_player_lists.py ..\Scripts\1491.50\script_rel src\data

Each output is a sorted list of "name", lines:

- WalkStyles.inc: literal names passed to _SET_PED_DESIRED_LOCO_MOTION_TYPE.
- Scenarios.inc: joaat("...") names of ped scenarios (WORLD_HUMAN_,
  PROP_HUMAN_, ...). Ransack, shop, vehicle and animal scenarios are left
  out because the player ped can't use them.
- Moods.inc: facial idle anim names starting with "mood_" (not the
  joaat("MOOD_<character>") hashes, which are something else).
- PostFx.inc: literal names passed to the ANIMPOSTFX_ natives.
- Timecycles.inc: literal names passed to the *TIMECYCLE_MODIFIER* natives.
- DamagePacks.inc: literal names passed to APPLY_PED_DAMAGE_PACK.
- Voices.inc: literal names passed to SET_AMBIENT_VOICE_NAME.
- Speeches.inc: ambient speech lines. The scripts reach
  PLAY_PED_AMBIENT_SPEECH_NATIVE through per-script wrappers called as
  func_N(ped, "LINE", <speech params hash>, ...), so a line is a literal
  in that position followed by a large integer that isn't a float bit
  pattern; plus literal `speechName = "LINE"` assignments.
- Animations.inc: { "dict", "anim" } pairs passed as literals to
  TASK_PLAY_ANIM / TASK_PLAY_ANIM_ADVANCED.
- Effects.inc: { "asset", "fx" } pairs: a literal non-looped particle effect
  started after a literal USE_PARTICLE_FX_ASSET in the same function. Most
  scripts load their asset by hash or as the script's own asset, so this
  finds few.

Names only reached through script data (struct fields, arrays) are
missed. Nothing here comes from Rampage.
"""
import os, re, struct, sys

SCENARIO_PREFIXES = ("WORLD_HUMAN_", "WORLD_PLAYER_", "WORLD_CAMP_", "PROP_HUMAN_",
                     "PROP_PLAYER_", "PROP_CAMP_", "GENERIC_", "MP_LOBBY_")

LISTS = {
    "WalkStyles.inc": [re.compile(r'_SET_PED_DESIRED_LOCO_MOTION_TYPE\([^;"]*?, "([^"]+)"\)')],
    "Scenarios.inc": [re.compile(r'joaat\("((?:%s)[A-Za-z0-9_]+)"\)' % "|".join(SCENARIO_PREFIXES), re.I)],
    "Moods.inc": [re.compile(r'(?<!joaat\()"(mood_[A-Za-z0-9_]+)"', re.I)],
    "PostFx.inc": [re.compile(r'ANIMPOSTFX_\w*\("([^"]+)"')],
    "Timecycles.inc": [re.compile(r'TIMECYCLE_MODIFIER\w*\("([^"]+)"')],
    "DamagePacks.inc": [re.compile(r'APPLY_PED_DAMAGE_PACK\([^;"]*?, "([^"]+)"')],
    "Voices.inc": [re.compile(r'SET_AMBIENT_VOICE_NAME\([^;"]*?, "([^"]+)"\)')],
    "Speeches.inc": [re.compile(r'speechName = "([A-Z][A-Z0-9_]+)"')],
}

SPEECH_CALL = re.compile(r'func_\d+\([^,()]+(?:\([^()]*\))?, "([A-Z][A-Z0-9_]+)", (-?\d+), ')
ANIM_CALL = re.compile(r'TASK_PLAY_ANIM(?:_ADVANCED)?\([^,]+, "([^"]+)", "([^"]+)"')
FX_CALL = re.compile(r'USE_PARTICLE_FX_ASSET\("([^"]+)"\)|START_(?:NETWORKED_)?PARTICLE_FX_NON_LOOPED_\w*\("([^"]+)"')
FUNCTION_START = re.compile(r'\n(?=\S[^\n]*\) // Position)')

def looks_like_float(value):
    f = struct.unpack("<f", struct.pack("<I", value & 0xFFFFFFFF))[0]
    return f == f and 1e-3 <= abs(f) <= 1e6 and abs(f * 100 - round(f * 100)) < 1e-3

def is_speech_params(value):
    return abs(value) >= 1000000 and not looks_like_float(value)

# Names that differ only in case are one name to the game; keep one spelling.
UPPER = {"Scenarios.inc"}

def main(src, dst):
    found = {name: {} for name in LISTS}
    pairs = {"Animations.inc": set(), "Effects.inc": set()}
    for fn in sorted(os.listdir(src)):
        if not fn.endswith(".c"):
            continue
        with open(os.path.join(src, fn), encoding="utf-8", errors="replace") as f:
            text = f.read()
        for name, patterns in LISTS.items():
            for rx in patterns:
                for m in rx.findall(text):
                    v = m.upper() if name in UPPER else m
                    found[name].setdefault(v.lower(), v)
        for line, params in SPEECH_CALL.findall(text):
            if is_speech_params(int(params)):
                found["Speeches.inc"].setdefault(line.lower(), line)
        for d, a in ANIM_CALL.findall(text):
            pairs["Animations.inc"].add((d.lower(), a))  # dictionary names ignore case
        for body in FUNCTION_START.split(text):
            asset = None
            for m in FX_CALL.finditer(body):
                if m.group(1):
                    asset = m.group(1)
                elif asset:
                    pairs["Effects.inc"].add((asset, m.group(2)))
    for name, values in found.items():
        write_inc(dst, name, ['"%s",' % v for _, v in sorted(values.items())])
    for name, values in pairs.items():
        write_inc(dst, name, ['{ "%s", "%s" },' % p for p in sorted(values)])

def write_inc(dst, name, rows):
    lines = ["// Generated by tools/extract_player_lists.py from the 1491.50 decompiled",
             "// scripts; don't edit by hand."] + rows
    with open(os.path.join(dst, name), "w", encoding="utf-8", newline="\r\n") as f:
        f.write("\n".join(lines) + "\n")
    print(name, len(rows))

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
