r"""Builds the ped model lists from the game's own decompiled scripts:

    python tools/extract_models.py ..\Scripts\1491.50 src\data

Collects every joaat("...") name in script_rel and script_mp_rel that has
a ped model prefix, lowercased and sorted:

- PedModels.inc: humans, as { "group", "model" } pairs; the group comes
  from the prefix (Ambient Male, Story, Gang, ...).
- HorseModels.inc: a_c_horse*, a_c_donkey* and a_c_horsemule* names.
- AnimalModels.inc: every other a_c_ name.

Some names with those prefixes aren't models (random-event names, MP
strings); the menus drop them at runtime with IS_MODEL_IN_CDIMAGE and
IS_MODEL_A_PED. Nothing here comes from Rampage.
"""
import os, re, sys

JOAAT = re.compile(r'joaat\("([A-Za-z0-9_]+)"\)')

# Prefix -> group, first match wins.
HUMAN_GROUPS = [
    ("player_", "Player"),
    ("a_m_", "Ambient Male"),
    ("a_f_", "Ambient Female"),
    ("cs_", "Story"),
    ("g_m_", "Gang"), ("g_f_", "Gang"),
    ("s_m_", "Service"), ("s_f_", "Service"),
    ("u_m_", "Unique"), ("u_f_", "Unique"),
    ("re_", "Random Events"),
    ("mp_", "Multiplayer"),
    ("msp_", "Mission"), ("mes_", "Mission"), ("rces_", "Mission"),
    ("amsp_", "Mission"), ("casp_", "Mission"), ("cr_", "Mission"),
    ("ge_", "Mission"),
]
# Ped models end in a variant number (_01, _02, ...) or are known singles.
HUMAN_SHAPE = re.compile(r'^[a-z0-9_]+_\d\d$|^cs_[a-z0-9_]+$|^player_(zero|three)$|^mp_(male|female)$')
HORSE_PREFIXES = ("a_c_horse", "a_c_donkey")

def main(script_dir, out_dir):
    names = set()
    for sub in ("script_rel", "script_mp_rel"):
        folder = os.path.join(script_dir, sub)
        for fn in os.listdir(folder):
            with open(os.path.join(folder, fn), encoding="utf-8", errors="replace") as f:
                names.update(n.lower() for n in JOAAT.findall(f.read()))
    humans, horses, animals = [], [], []
    for n in sorted(names):
        if n.startswith("a_c_"):
            (horses if n.startswith(HORSE_PREFIXES) else animals).append(n)
            continue
        for prefix, group in HUMAN_GROUPS:
            if n.startswith(prefix) and HUMAN_SHAPE.match(n):
                humans.append((group, n))
                break
    header = "// Generated by tools/extract_models.py from the 1491.50 decompiled\n// scripts; don't edit by hand.\n"
    def write(name, lines):
        with open(os.path.join(out_dir, name), "w", encoding="utf-8", newline="\r\n") as f:
            f.write(header + "".join(l + "\n" for l in lines))
    write("PedModels.inc", ['{ "%s", "%s" },' % (g, n) for g, n in sorted(humans)])
    write("HorseModels.inc", ['"%s",' % n for n in horses])
    write("AnimalModels.inc", ['"%s",' % n for n in animals])
    print(len(humans), "humans,", len(horses), "horses,", len(animals), "animals")

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
