r"""Builds the Ped Editor's and the Horse menu's lists from the game's own
decompiled scripts:

    python tools/extract_peds.py ..\Scripts\1491.50 src\data

- HorseTack.inc: { "group", "HORSE_EQUIPMENT_..." } for every horse tack
  shop item the scripts name, grouped by the word after HORSE_EQUIPMENT_
  (saddle families, BLANKET, BEDROLL, ...), from both the singleplayer
  and online scripts (the shop catalogue is shared). Invalid ones are
  filtered at runtime.
- CombatStyles.inc / CombatStyleMods.inc: literal joaat names passed to
  _SET_PED_COMBAT_STYLE and _SET_PED_COMBAT_STYLE_MOD.

Nothing here comes from Rampage.
"""
import os, re, sys

TACK = re.compile(r'"(HORSE_EQUIPMENT_[A-Z0-9_]+)"', re.I)
STYLE = re.compile(r'_SET_PED_COMBAT_STYLE\([^,]*, joaat\("([^"]+)"\)')
MOD = re.compile(r'_SET_PED_COMBAT_STYLE_MOD\([^,]*, joaat\("([^"]+)"\)')

SADDLES = {"CHARRO", "MCCLELLAN", "MOTHERHUBBARD", "WESTERN", "MOONSHINERSADDLE"}

def group(name):
    word = re.sub(r'^HORSE_EQUIPMENT_(HORSE_)?', '', name).split('_')[0]
    if word in SADDLES:
        return "Saddles"
    if word in ("MALE", "FEMALE"):
        return "Other"
    return word.capitalize() + "s" if not word.endswith("S") else word.capitalize()

def main(script_dir, out_dir):
    tack, styles, mods = set(), set(), set()
    # Tack comes from the online scripts too: the shop catalogue is shared,
    # and singleplayer's scripts only name a few items.
    for sub in ("script_rel", "script_mp_rel"):
        folder = os.path.join(script_dir, sub)
        for fn in os.listdir(folder):
            with open(os.path.join(folder, fn), encoding="utf-8", errors="replace") as f:
                text = f.read()
            tack.update(t.upper() for t in TACK.findall(text))
            if sub == "script_rel":
                styles.update(s.upper() for s in STYLE.findall(text))
                mods.update(m.upper() for m in MOD.findall(text))
    header = "// Generated by tools/extract_peds.py from the 1491.50 decompiled\n// scripts; don't edit by hand.\n"
    def write(name, lines):
        with open(os.path.join(out_dir, name), "w", encoding="utf-8", newline="\r\n") as f:
            f.write(header + "".join(l + "\n" for l in lines))
    write("HorseTack.inc", ['{ "%s", "%s" },' % (group(t), t) for t in sorted(tack, key=lambda t: (group(t), t))])
    write("CombatStyles.inc", ['"%s",' % s for s in sorted(styles)])
    write("CombatStyleMods.inc", ['"%s",' % m for m in sorted(mods)])
    print(len(tack), "tack items,", len(styles), "combat styles,", len(mods), "combat style mods")

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
