r"""Builds src/data/MetaPedExpressions.inc, the named MetaPedExpression ids
for _SET_CHAR_EXPRESSION, from the full list alloc8or's native DB links in
that native's comment (https://pastebin.com/Ld76cAn7):

    curl -s https://pastebin.com/raw/Ld76cAn7 > expr.txt
    python tools/extract_expressions.py expr.txt src\data

Each line there is "<decimal id>,  -- <description>". Unnamed ids are
skipped. Output rows are { id, "Name", horse } with horse true for the
horse-only ids (description starts with "horse").
"""
import os, re, sys

LINE = re.compile(r'^\s*(\d+),\s*--\s*(.+?)\s*$')

def main(src, out_dir):
    rows = []
    for line in open(src, encoding="utf-8"):
        m = LINE.match(line)
        if not m:
            continue
        desc = m.group(2)
        horse = desc.startswith("horse ")
        name = desc[6:] if horse else desc
        name = name[0].upper() + name[1:]
        rows.append('{ %s, "%s", %s },' % (m.group(1), name.replace('"', "'"), "true" if horse else "false"))
    with open(os.path.join(out_dir, "MetaPedExpressions.inc"), "w", encoding="utf-8", newline="\r\n") as f:
        f.write("// Generated by tools/extract_expressions.py from the MetaPedExpression list\n"
                "// alloc8or's native DB links (https://pastebin.com/Ld76cAn7); don't edit by hand.\n")
        f.write("".join(r + "\n" for r in rows))
    print(len(rows))

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
