r"""Builds the World submenus' lists from the game's own decompiled scripts:

    python tools/extract_world.py ..\Scripts\1491.50 src\data

- Ipls.inc: { 0xHASH, "name" } for every IPL the scripts request or
  remove by literal (REQUEST_IPL_HASH(...), REMOVE_IPL_HASH(...), ...);
  the name is filled in when the literal is joaat("...").
- Doors.inc: door hashes passed as literals to the door system natives
  (DOOR_SYSTEM_*, ADD_DOOR_TO_SYSTEM_NEW, IS_DOOR_REGISTERED_WITH_SYSTEM).
  The menu lists the ones registered when it opens.

Nothing here comes from Rampage.
"""
import os, re, sys

IPL_CALL = re.compile(r'(?:REQUEST|REMOVE)_IPL\w*\((-?\d+|joaat\("([^"]+)"\))\)')
DOOR_CALL = re.compile(r'(?:DOOR_SYSTEM_\w+|ADD_DOOR_TO_SYSTEM_NEW|IS_DOOR_REGISTERED_WITH_SYSTEM)\((-?\d{5,})')

def joaat(s):
    h = 0
    for c in s.lower().encode():
        h = (h + c) & 0xFFFFFFFF
        h = (h + (h << 10)) & 0xFFFFFFFF
        h ^= h >> 6
    h = (h + (h << 3)) & 0xFFFFFFFF
    h ^= h >> 11
    return (h + (h << 15)) & 0xFFFFFFFF

def main(script_dir, out_dir):
    ipls, doors = {}, set()
    for sub in ("script_rel", "script_mp_rel"):
        folder = os.path.join(script_dir, sub)
        for fn in os.listdir(folder):
            with open(os.path.join(folder, fn), encoding="utf-8", errors="replace") as f:
                text = f.read()
            for literal, name in IPL_CALL.findall(text):
                if name:
                    ipls[joaat(name)] = name.lower()
                else:
                    ipls.setdefault(int(literal) & 0xFFFFFFFF, "")
            doors.update(int(v) & 0xFFFFFFFF for v in DOOR_CALL.findall(text))
    header = "// Generated by tools/extract_world.py from the 1491.50 decompiled\n// scripts; don't edit by hand.\n"
    def write(name, lines):
        with open(os.path.join(out_dir, name), "w", encoding="utf-8", newline="\r\n") as f:
            f.write(header + "".join(l + "\n" for l in lines))
    write("Ipls.inc", ['{ 0x%08X, "%s" },' % (h, n) for h, n in sorted(ipls.items())])
    write("Doors.inc", ['0x%08X,' % h for h in sorted(doors)])
    print(len(ipls), "IPLs,", len(doors), "doors")

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
