r"""Builds the object spawner lists from the game's own decompiled scripts:

    python tools/extract_objects.py ..\Scripts\1491.50 src\data

From every joaat("...") name in script_rel and script_mp_rel, lowercased
and sorted:

- ObjectModels.inc: p_ and s_ names (props and inventory models). Some
  aren't models; the menu drops those at runtime with IS_MODEL_IN_CDIMAGE.
- Propsets.inc: pg_ names (propsets).
- Composites.inc: COMPOSITE_LOOTABLE_..._DEF names (herb and lootable
  composites, for the Plant Spawner).

Nothing here comes from Rampage.
"""
import os, re, sys

JOAAT = re.compile(r'joaat\("([A-Za-z0-9_]+)"\)')

def main(script_dir, out_dir):
    names = set()
    for sub in ("script_rel", "script_mp_rel"):
        folder = os.path.join(script_dir, sub)
        for fn in os.listdir(folder):
            with open(os.path.join(folder, fn), encoding="utf-8", errors="replace") as f:
                names.update(n.lower() for n in JOAAT.findall(f.read()))
    objects = sorted(n for n in names if n.startswith(("p_", "s_")))
    propsets = sorted(n for n in names if n.startswith("pg_"))
    composites = sorted(n.upper() for n in names if n.startswith("composite_lootable_") and n.endswith("_def"))
    header = "// Generated by tools/extract_objects.py from the 1491.50 decompiled\n// scripts; don't edit by hand.\n"
    def write(name, lines):
        with open(os.path.join(out_dir, name), "w", encoding="utf-8", newline="\r\n") as f:
            f.write(header + "".join('"%s",\n' % l for l in lines))
    write("ObjectModels.inc", objects)
    write("Propsets.inc", propsets)
    write("Composites.inc", composites)
    print(len(objects), "objects,", len(propsets), "propsets,", len(composites), "composites")

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
