r"""Builds src/data/EffectPresets.inc, Player > Effects' named presets, from
Rampage's Effects menu (SubEffects).

    python tools/extract_rampage_effects.py <Rampage.asi> tools/rampage_inventory.csv src/data/EffectPresets.inc

Each preset row's handler is a three-instruction thunk: the scale in xmm2,
the effect name in rdx, the asset in rcx, then a jump to the shared
play-effect function. The handler addresses come from the inventory
(tools/rampage_inventory.py); the thunks are read with capstone. Needs
pefile and capstone.

The names are carried over on purpose (see CLAUDE.md); nothing reads
Rampage at runtime. Output rows:
    { "<label>", "<asset>", "<effect>", scale },
"""
import csv
import struct
import sys

import capstone
import pefile
from capstone import x86


def main(asi, inventory, out):
    pe = pefile.PE(asi, fast_load=True)
    base = pe.OPTIONAL_HEADER.ImageBase
    read = lambda va, n: pe.get_data(va - base, n)
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_64)
    md.detail = True

    rows = []
    with open(inventory, newline='', encoding='utf-8') as f:
        for r in csv.reader(f):
            if len(r) > 8 and r[1] == 'SubEffects' and r[3] == 'action' and r[8]:
                rows.append((r[4], int(r[8].split()[0], 16)))

    lines = []
    for label, ea in rows:
        regs = {}
        for i in md.disasm(read(ea, 0x40), ea):
            if i.mnemonic == 'jmp':
                break
            dst, src = i.operands
            if src.type != x86.X86_OP_MEM or src.mem.base != x86.X86_REG_RIP:
                regs = None
                break
            addr = i.address + i.size + src.mem.disp
            name = i.reg_name(dst.reg)
            if i.mnemonic == 'movss':
                regs[name] = struct.unpack('<f', read(addr, 4))[0]
            elif i.mnemonic == 'lea':
                regs[name] = read(addr, 128).split(b'\0')[0].decode('ascii')
        if not regs or not {'rcx', 'rdx'} <= regs.keys():
            continue  # not a preset thunk (Play Effect, Custom rows)
        scale = regs.get('xmm2', 1.0)
        lines.append(f'{{ "{label}", "{regs["rcx"]}", "{regs["rdx"]}", {scale:.1f}f }},')

    with open(out, 'w', newline='\r\n', encoding='utf-8') as f:
        f.write('// Generated by tools/extract_rampage_effects.py from Rampage\'s Effects\n')
        f.write('// menu. Regenerate rather than edit.\n')
        f.write('// { label, asset, effect, scale }\n')
        f.write('\n'.join(lines) + '\n')
    print(f'{len(lines)} presets')


if __name__ == '__main__':
    main(*sys.argv[1:4])
