"""Regenerates docs/PORTING.md from tools/rampage_inventory.csv and the STATUS
table below. Update STATUS as submenus are ported, then run:

    python tools/porting_status.py
"""
import csv,collections,sys
rows=list(csv.DictReader(open('tools/rampage_inventory.csv',encoding='utf-8')))
INTER={"action","toggle","toggle_plain","toggle_value","toggle_cb","choice","slider_float","slider_int","number_int","value_hex","value_pick","color","action_icon","component_pick","posse_item","location"}
cnt=collections.Counter(); area={}
for r in rows:
    area[r['submenu']]=r['area']
    if r['kind'] in INTER: cnt[r['submenu']]+=1
# Areas the user has set aside for now; their submenus show as Tabled unless STATUS says otherwise.
TABLED_AREAS = {'Debug','Object Editor','Script Tools'}
STATUS = {
 'SubSelf':('Done','Player'),
 'SubSelfHorse':('Done','Horse'),
 'SubSelfScenarios':('Done','Player > Scenarios: list from the game scripts plus Custom Input/Search; no Scenarios.txt reload'),
 'SubSelfWardrobe':('Done','Player > Wardrobe: clothing list from a user-supplied Rampagio_ClothingDb.xml (same format as Rampage); Keep Facial Hair is a toggle instead of holding Shift (ours)'),
 'SubSelfWardrobeComponent':('Done','Player > Wardrobe > Components > <category>: picking an item applies it, then opens its wearable states (ours)'),
 'SubSelfWardrobeWearableState':('Done','Player > Wardrobe > Components > Wearable State'),
 'SubSelfOutfitSaver':('Done','Player > Wardrobe > Outfits: saved in Rampagio_Outfits.json (ours; Rampage writes an XML per outfit)'),
 'SubSelfFacialHair':('Done','Player > Wardrobe > Hair and Weight'),
 'SubSelfPedMetaTags':('Done','Player > Wardrobe > Meta Ped Tags'),
 'SubSelfPedMetaExpressions':('Done','Player > Wardrobe > Meta Ped Expressions: names from the MetaPedExpression list alloc8or links'),
 'SubSelfCustomizations':('Done','Player > Wardrobe > Overlay Textures: TX Id and Palette Id pick from the tables of Rampage (data/OverlayTextures.inc); the hashes can also be typed in'),
 'SubSelfModelChanger':('Partial','Player > Wardrobe > Model Changer: Force Player Type not ported'),
 'SubModelChangerPeds':('Done','Player > Wardrobe > Model Changer > Humans: models from the game scripts, grouped by prefix'),
 'SubModelChangerPedsList':('Done','Player > Wardrobe > Model Changer > Humans > <group>'),
 'SubModelChangerHorses':('Done','Player > Wardrobe > Model Changer > Horses: one list from the game scripts'),
 'SubModelChangerHorsesList':('Done','Player > Wardrobe > Model Changer > Horses'),
 'SubModelChangerAnimal':('Done','Player > Wardrobe > Model Changer > Animals: one list from the game scripts'),
 'SubSelfWalkStyles':('Done','Player > Wardrobe > Walk Styles: list from the game scripts'),
 'SubDamagePacks':('Done','Player > Wardrobe > Apply Damage Packs: list from the game scripts'),
 'SubTimecycleMod':('Done','Player > Vision > Timecycle Modifiers: list from the game scripts'),
 'SubAnimPostFx':('Done','Player > Vision > Screen Effects: list from the game scripts'),
 'SubMoods':('Done','Player > Moods: mood_ anims from the game scripts'),
 'SubAbilities':('Done','Player > Abilities: recharge toggles restore 1.0 when off (ours)'),
 'SubSelfAnimationsCustom':('Done','Player > Animations > Custom Animations: the Custom Flag submenu is a typed Custom Flags row (decimal or 0x hex)'),
 'SubSelfAnimationsDicts':('Done','Player > Animations > Dictionaries: script list plus Rampagio_PedAnimList.txt, re-read on open instead of Reload List'),
 'SubAnimationDictsList':('Done','Player > Animations > Dictionaries > (dictionary): picking one also fills in Custom Animations (ours)'),
 'SubSelfFacialAnimations':('Done','Player > Animations > Facial Animations'),
 'SubEffects':('Done','Player > Effects: the 25 Rampage presets (data/EffectPresets.inc), Scale, Loop, Custom, plus 6 effects from the game scripts'),
 'SubEmotes':('Done','Player > Emotes: every emote type listed under its own heading instead of an Emote Type choice; adds gun twirls (alloc8or eEmote list)'),
 'SubPlaySpeech':('Done','Player > Play Speech'),
 'SubPlaySpeechRegular':('Done','Player > Play Speech > Regular Speeches: 208 lines from the game scripts (Rampage\'s table has 502); one Display All for every list'),
 'SubPlaySpeechFlowgreet':('Done','Player > Play Speech > Flow Greets: Rampagio_SpeechFlowGreets.txt, re-read on open'),
 'SubPlaySpeechVignettes':('Done','Player > Play Speech > Vignettes: Rampagio_SpeechVignettes.txt, re-read on open'),
 'SubPlaySpeechCustom':('Done','Player > Play Speech > Custom Speeches: Rampagio_SpeechList.txt, re-read on open'),
 'SubVoiceChanger':('Done','Player > Play Speech > Voice Changer: Set Voice lists the script voices plus Custom Input (ours)'),
 'SubPlayerProofs':('Done','Player > Player Proofs: re-applied every frame (ours)'),
 'SubPlayerConfigFlags':('Done','Player > Config Flags: flag by number (no names), shows current state (ours)'),
 'SubPlayerPosse':('Done','Player > Posse: commands are menu rows, bindable to keys with F11 (Settings > Hotkey Manager); Add Aimed/Nearest Ped, Teleport, Dismiss and Delete rows (ours)'),
 'SubVehicle':('Done','Vehicle: Invincible Vehicle re-applies to the current vehicle every frame (ours); Fly Speed and Ground Force are separate rows'),
 'SubVehiclePv':('Done','Vehicle > Blip'),
 'SubVehicleAI':('Done','Vehicle > Vehicle AI'),
 'SubVehicleChaffeur':('Done','Vehicle > Chauffeur'),
 'SubVehiclePaintOptions':('Done','Vehicle > Paint Options'),
 'SubVehiclePropsets':('Done','Vehicle > Propsets: every vehicle propset the game scripts name (tools/extract_vehicles.py) instead of a per-model table'),
 'SubVehicleExtras':('Done','Vehicle > Customization'),
 'SubTrainCreator':('Done','Vehicle > Train Creator: the 23 train configs the game scripts use, shown by hash and car count (Rampage has 28 named ones in its own table)'),
 'SubTrainWhistle':('Done','Vehicle > Train Creator > Whistle'),
 'SubPedSpawner':('Done','Spawner > Ped Spawner: models from the game scripts; Hijack Ped adds the first ped of a typed model to the database'),
 'SubPedSpawnerSettings':('Done','Spawner > Ped Spawner > Spawner Settings: Scale and Health are a toggle plus a value row each'),
 'SubPedSpawnerDatabase':('Done','Spawner > Ped Spawner > Ped Database: per-ped actions, and Ped Editor opens the full editor'),
 'SubPedSpawnerPeds':('Done','Spawner > Ped Spawner > Humans: grouped by model prefix'),
 'SubPedSpawnerPedsList':('Done','Spawner > Ped Spawner > Humans > <group>'),
 'SubPedSpawnerHorses':('Done','Spawner > Ped Spawner > Horses: one list from the game scripts'),
 'SubPedSpawnerAnimal':('Done','Spawner > Ped Spawner > Animals: Legendary Animals are the table of Rampage (model plus outfit preset, data/LegendaryAnimals.inc); Fishes gets its legendary fish too'),
 'SubPedSpawnerFish':('Done','Spawner > Ped Spawner > Fishes'),
 'SubPedSpawnerAddon':('Done','Spawner > Ped Spawner > Addon Peds: Rampagio_AddonPeds.txt, re-read on open'),
 'SubPedSpawnerDispatch':('Done','Spawner > Law Dispatch Spawner: LAW_ responses from the game scripts plus the table of Rampage, which also sets the law region of each response (data/LawDispatchRegions.inc)'),
 'SubVehicleSpawner':('Partial','Spawner > Vehicle Spawner: lists by type from the game scripts; settings are ours; JSON Loader not ported'),
 'SubObjectSpawner':('Done','Spawner > Object Spawner: objects from the game scripts; creator cam is our own free cam'),
 'SubObjSpawnerDatabase':('Done','Spawner > Object Spawner > Object Database: per-object actions (ours) until the Object Editor is back'),
 'SubObjSpawnerAllObjs':('Done','Spawner > Object Spawner > All Objects: game script objects plus Rampagio_ObjectList.txt'),
 'SubObjSpawnerPropsets':('Done','Spawner > Object Spawner > Propsets: pg_ names from the game scripts'),
 'SubObjSpawnerLoadSave':('Partial','Spawner > Object Spawner > Load / Save: objects only, in Rampagio_Spooner.json (ours); no spooner XML, peds or vehicles'),
 'SubPlantSpawner':('Done','Spawner > Plant Spawner: the 84 COMPOSITE_LOOTABLE_ composites the scripts name'),
 'SubTeleport':('Done','Teleport: Common Locations, Camps and Safe Houses and the region submenus from the Rampage lists (data/Teleports.inc); Blips reads the location and mission blip globals Rampage reads (1491.50 indices) and names them from its table (data/BlipLabels.inc)'),
 'SubTeleportCustom':('Done','Teleport > Load Custom / Delete Custom'),
 'SubWorld':('Done','World: also the Cloud Editor and Ambient Light submenus (unnamed builders in Rampage)'),
 'SubWorldOcean':('Done','World > Water'),
 'SubWorldLocalPeds':('Done','World > Ped Manager: scanner labels instead of the ESP toggle; Hostile Peds gives a repeater (Rampage picks from its own weapon list)'),
 'SubWorldLocalVehicles':('Done','World > Vehicle Manager: scanner labels instead of the ESP toggle'),
 'SubWorldLocalObjects':('Partial','World > Object Manager: Object Finder belongs to the tabled Object Editor area'),
 'SubWorldDoorManager':('Done','World > Door Manager: the doors the game scripts name, listed when registered (Rampage uses its own door table)'),
 'SubWorldTornado':('Done','World > Tornado & Black Hole: own force maths; meteors use script rock models'),
 'SubWorldIMAPLoader':('Done','World > IPL Loader: Map Sets lists the 173 IPLs the game scripts load (Rampage has its own set table); interior entity sets by name'),
 'SubIMAPCustom':('Done','World > IPL Loader > Custom: Rampagio_IPLList.xml (same format as Rampage)'),
 'SubIMAPCustomSet':('Done','World > IPL Loader > IPL Sets: XML set files in a RampagioIPLS folder, same format as the IPLS folder of Rampage'),
 'SubWorldStates':('Done','World > World States: by state id (Global_40.f_283 bitset), no names'),
 'SubWorldTime':('Done','World > Time'),
 'SubRecoveryMoney':('Done','Recovery > Money: drop is a timed toggle (ours) instead of every tick'),
 'SubRecoveryHonor':('Partial','Recovery > Honor: all actions; current honor reads honor_current; honor HUD meter not shown'),
 'SubRecoveryBounty':('Done','Recovery > Bounty: state rows also show each state bounty (ours)'),
 'SubRecoveryCores':('Done','Recovery > Cores: temporary rank applies on every step (ours)'),
 'SubRecoveryAddItems':('Done','Recovery > Add Items: Unlimited Items also blocks by-GUID removals (ours)'),
 'SubRecoveryGiveItemsList':('Done','Recovery > Add Items > Give Items: own item list from the game scripts (tools/extract_items.py); method is a visible choice instead of Shift (ours)'),
 'SubRecoveryUnlocks':('Done','Recovery > Unlocks: own lists from the game scripts (tools/extract_unlocks.py); Unlock Checks lists every unlock the scripts name; Add Entries writes every journal entry the game allows; Discover Fish skips legendary outfit presets (ours)'),
 'SubUnlockCheats':('Done','Recovery > Unlocks > Cheat Codes: activates each cheat through the game cheat state instead of showing its phrase (ours)'),
 'SubCollectiblesCigaretteCards':('Done','Recovery > Collectibles > Cigarette Cards: sets and card models from the game (CARD_SET_* collectables, s_inv_cigcard_* models); Auto Collect All runs as a stoppable per-frame job (ours)'),
 'SubCollectiblesCigaretteCardsSet':('Done','Recovery > Collectibles > Cigarette Cards > <set>: cards by in-game name with owned count; Give Missing Cards (ours)'),
 'SubCollectiblesDinoBones':('Done','Recovery > Collectibles > Dino Bones: read from the dino_bones collectable category with _COLLECTABLE_GET_PLACEMENT_LOCATION; locations in a Locations list'),
 'SubCollectiblesDreamcatchers':('Done','Recovery > Collectibles > Dreamcatchers: coordinates from discoverable_generic_location (tools/extract_collectibles.py), found state from Global_40.f_8863.f_148'),
 'SubCollectiblesRockCarvings':('Done','Recovery > Collectibles > Rock Carvings: read from the rock_carvings collectable category; locations in a Locations list'),
 'SubMapDiscoverables':('Done','Recovery > Unlocks > Map Discoverables: the 284 of Rampage discoveries (data/RampageMapDiscoveries.inc) plus any more the scripts name'),
 'SubWorldWeather':('Done','World > Weather'),
 'SubWeapons':('Done','Weapon: Rope Gun pulls toward the impact and Portal Gun uses markers (ours)'),
 'SubWeaponsManage':('Done','Weapon > Manage Weapons: Upgrade Weapon tries the COMPONENT_ names from the game scripts'),
 'SubWeaponsGive':('Done','Weapon > Manage Weapons > Give Weapon'),
 'SubWeaponsAmmunition':('Done','Weapon > Ammunition: Drop Ammo offers six PICKUP_AMMO_ kinds from the game scripts'),
 'SubWeaponModifiers':('Done','Weapon > Weapon Modifiers: Weapon Scale re-applies on weapon switch (ours); Skill sets the current weapon stat'),
 'SubMiscellaneous':('Partial','Miscellaneous: Air Walk holds a fixed height (ours); Take a Photo saves without the district/state photo stats; About lives in Settings; Global Editor and Script Tools rows wait for the tabled Script Tools area'),
 'SubMusicPlayer':('Done','Miscellaneous > Music Player: Windows MCI on files in a RampagioMusic folder (ours; Rampage bundles FMOD)'),
 'SubGameMusic':('Done','Miscellaneous > Game Music: 314 music events from the game scripts'),
 'SubMobileTheater':('Done','Miscellaneous > Mobile Theater: screen position and size rows (ours)'),
 'SubCutscenePlayer':('Partial','Miscellaneous > Cutscene Player: 428 mission cutscenes from the game scripts; Try to Populate (Rampage model table) and the Red Dead Online list not ported'),
 'SubMinigames':('Done','Miscellaneous > Minigames > Undead Nightmare II: own wave logic (kill count spawns bosses) on the models and bosses Rampage uses'),
 'SubEditVolume':('Done','Miscellaneous > Volume Editor: edits volumes created there (ours); relationship groups from the game scripts'),
 'SubFriendlist':('Dropped','Online only (Social Club friends)'),
 'SubStatEditor':('Done','Miscellaneous > Stat Editor'),
 'SubSettings':('Partial','Settings: Search, Core, Theme, Hotkey Manager (F11 on a row binds it, ours), Load / Save; Gamepad Open Key is a combo choice; Plugins and Language have no Rampagio counterpart'),
 'SubSettingsCore':('Partial','Settings > Core: Gamepad Controls, Menu Sounds, Show Controller Screen; Mouse Controls still to come (CLAUDE.md UI direction); welcome/ToS/update/landing rows dropped'),
 'SubSettingsLoadSave':('Done','Settings > Load / Save: Rampagio.json'),
 'SubSettingsColor':('Partial','Settings > Theme: eight colors, menu position and Max Display Options; no font choice or menu title text'),
 'SubSettingsPremadeThemes':('Done','Settings > Theme > Premade Themes: our own seven presets (Rampage has 26 of its own)'),
 'SubSettingsCustomThemes':('Done','Settings > Theme > Custom Themes: the themes component of Rampagio.json'),
 'SubSettingsXUI':('Partial','Settings > Theme > Max Display Options; teleport map, spawner previews, ink rendering, inverted colors and centered title not ported'),
 'SubWindowManager':('Tabled','ImGui windows (log, sysinfo, performance, hotkeys): waits for the ImGui overlay'),
 'SubOverlaySettings':('Done','Settings > Overlay Settings'),
 'SubCreatorSettings':('Done','Spawner > Object Spawner > Cam Settings'),
 'SubLanguageManager':('Dropped','The label translation files of Rampage; Rampagio has no translated labels'),
 'SubAbout':('Done','Settings > About Rampagio (our own credits)'),
 'SubHorseBlip':('Done','Horse > Blip'),
 'SubHorseLoader':('Done','Horse > Horse Loader: model, meta tags and gender in Rampagio_Horses.json (ours)'),
 'SubHorsePedMetaExpressions':('Done','Horse > Meta Ped Expressions: the horse expressions of the shared menu'),
 'SubHorsePedMetaTags':('Done','Horse > Meta Ped Tags: the shared menu with Index / Load Data from Index'),
 'SubHorseStats':('Done','Horse > Horse Stats: ranks 0-10 per attribute'),
 'SubMobileStable':('Done','Horse > Mobile Stable: 280 HORSE_EQUIPMENT_ items from the game scripts, grouped by kind'),
 'SubMobileStableComponent':('Partial','Horse > Mobile Stable > <kind>: picking applies the item; no per-item tint picks'),
 'SubPedEditor':('Done','Ped Editor (from Spawner > Ped Database and World > Ped Manager): Attach To Something offers player, horse and nearest entities (ours)'),
 'SubPedEditorGeneral':('Done','Ped Editor > General'),
 'SubPedEditorCombat':('Done','Ped Editor > General > Combat Style: 27 styles and 10 mods from the game scripts'),
 'SubPedEditorCombatAttributes':('Done','Ped Editor > General > Combat Style > Combat Attributes: by number, 0-127'),
 'SubPedEditorWeapons':('Done','Ped Editor > Weapons'),
 'SubPedEditorWeaponsGive':('Done','Ped Editor > Weapons > Give Weapon'),
 'SubPedPositioning':('Done','Ped Editor > Positioning: position and heading, or attachment offsets while attached'),
 'SubPedSelectAttachment':('Done','Ped Editor > Attach To Something (ours: player, horse, nearest ped/vehicle/object)'),
 'SubPedEditorWardrobe':('Done','Ped Editor > Wardrobe: own rows plus links to the shared wardrobe menus'),
 'SubPedEditorWardrobeComponent':('Done','Ped Editor > Wardrobe > Components: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorWardrobeWearableState':('Done','Ped Editor > Wardrobe > Components > Wearable State: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorDamagePacks':('Done','Ped Editor > Wardrobe > Apply Damage Packs: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorWalkStyles':('Done','Ped Editor > Wardrobe > Walk Styles: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorMetaTags':('Done','Ped Editor > Wardrobe > Meta Ped Tags: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorMetaExpressions':('Done','Ped Editor > Wardrobe > Meta Ped Expressions: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorEffects':('Done','Ped Editor > Effects: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorEmotes':('Done','Ped Editor > Emotes: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorScenarios':('Done','Ped Editor > Scenarios: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorAnimationsCustom':('Done','Ped Editor > Animations > Custom Animations: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorAnimationsDicts':('Done','Ped Editor > Animations > Dictionaries: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorAnimationDictsList':('Done','Ped Editor > Animations > Dictionaries > (dictionary): the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorFacialAnimations':('Done','Ped Editor > Animations > Facial Animations: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorPlaySpeech':('Done','Ped Editor > Play Speech: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorPlaySpeechRegular':('Done','Ped Editor > Play Speech > Regular Speeches: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorPlaySpeechFlowgreet':('Done','Ped Editor > Play Speech > Flow Greets: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorPlaySpeechVignettes':('Done','Ped Editor > Play Speech > Vignettes: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorPlaySpeechCustom':('Done','Ped Editor > Play Speech > Custom Speeches: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubPedEditorVoiceChanger':('Done','Ped Editor > Play Speech > Voice Changer: the shared Player menu, opened from the Ped Editor (Menus::Target)'),
 'SubWeaponVisuals':('Partial','Weapon > Weapon Visuals: crosshair sprites and colour, arrow trails, condition; Disable Hitmarker / Hit Feedback (Rampage byte patches) not ported'),
 'SubWeaponsAimbot':('Done','Weapon > Aimbot: target filter (all/humans/animals) and Ignore Dying Peds are ours'),
 'SubWeaponsBullets':('Done','Weapon > Weapon Bullets: Particle Gun uses the script effects list; Ped / Vehicle Gun models and Remote Cannonball steering are ours'),
 'SubTeleportShopsandStuff':('Done','Teleport > Shops and Services: the Rampage list, 14 categories, 67 locations (data/Teleports.inc)'),
}
out=['# Porting status','','Each Rampage submenu (`Submenus::SubXxx`, see `tools/rampage_inventory.md`) and where Rampagio has it.','"Options" counts Rampage\'s static interactive rows. Statuses: Done (every row has an equivalent), Partial, Pending, Tabled (set aside for now), Dropped (online only, or Rampage infrastructure with no Rampagio counterpart). Nothing is live-tested yet.','']
by=collections.defaultdict(list)
for s in sorted(set(area)): by[area[s]].append(s)
tot=collections.Counter()
for a in sorted(by):
    out+=['## '+a,'','| Rampage submenu | Options | Status | Rampagio |','|---|---|---|---|']
    for s in by[a]:
        st,where=STATUS.get(s,('Tabled' if a in TABLED_AREAS else 'Pending',''))
        tot[st]+=1
        out.append('| %s | %d | %s | %s |'%(s,cnt[s],st,where))
    out.append('')
out[5:5]=['Submenus: %d done, %d partial, %d pending, %d tabled, %d dropped.'%(tot['Done'],tot['Partial'],tot['Pending'],tot['Tabled'],tot['Dropped']),'']
open('docs/PORTING.md','w',encoding='utf-8',newline='\r\n').write('\n'.join(out)+'\n')
print(tot)
