/*
	The text under the selected row (Rampage's row descriptions): looked up
	by the row's menu title and caption, so rows don't each carry it.
	kOurs in Descriptions.cpp (rows that are ours or work differently)
	wins over src/data/Descriptions.inc (Rampage's, generated by
	tools/extract_rampage_descriptions.py); kMenuAliases maps our menu
	titles that differ from Rampage's. Comparison ignores case and
	~COLOR_...~ codes. Lines are separated by '\n'; the menu wraps them to
	its width. A row can also set its own (Ui::Describe,
	MenuItemBase::SetDescription).
	tools/description_coverage.py lists rows without one.
*/

#pragma once

#include <string_view>

namespace Descriptions
{
	// The description for `caption` in the menu titled `menu`, or empty.
	std::string_view Find(std::string_view menu, std::string_view caption);
}
